# Generated by Django 2.1.1 on 2018-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Diametr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Massa_v_pog_metre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Moment_inercii',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Moment_soprotivleniya',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Ploshad_poperechnogo_sech',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Radius_inercii',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Statisticheskiy_moment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Tolshuna_stenki',
            field=models.FloatField(),
        ),
    ]
