# Generated by Django 2.1.1 on 2018-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0002_auto_20180927_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='gost_sortamenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
