# Generated by Django 2.1.1 on 2018-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0003_gost_sortamenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gost_sortamenta',
            old_name='text',
            new_name='GOST',
        ),
    ]
