# Generated by Django 2.1.1 on 2018-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0005_gost_sortamenta_gost_naz'),
    ]

    operations = [
        migrations.AddField(
            model_name='truby_gost_10704_91',
            name='Gost_naz',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
