# Generated by Django 2.1.1 on 2018-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0006_truby_gost_10704_91_gost_naz'),
    ]

    operations = [
        migrations.AddField(
            model_name='gost_sortamenta',
            name='type',
            field=models.CharField(choices=[('Труба', 'Труба'), ('Двутавр', 'Двутавр')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
