# Generated by Django 2.1.1 on 2018-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0007_gost_sortamenta_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='dvutavr_gost_8239_89',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_dvutavra', models.IntegerField()),
                ('vysota_h', models.IntegerField()),
                ('shirina_pilki_b', models.IntegerField()),
                ('tolshina_stenki_s', models.FloatField()),
                ('srednyaya_tolsina_polki_t', models.FloatField()),
                ('radius_vnutrennego_zakrugleniya_R', models.FloatField()),
                ('radius_zakrugleniya_polki_r', models.FloatField()),
                ('ploshad_poer_sech_A', models.FloatField()),
                ('massa_m', models.FloatField()),
                ('mom_iner_Ix', models.IntegerField()),
                ('mom_sopr_Wx', models.FloatField()),
                ('radius_iner_i_x', models.FloatField()),
                ('stat_mom_polu_sech_Sx', models.FloatField()),
                ('mom_iner_Iy', models.IntegerField()),
                ('mom_sopr_Wy', models.FloatField()),
                ('radius_iner_i_y', models.FloatField()),
                ('Gost_naz', models.CharField(max_length=250)),
            ],
        ),
    ]
