# Generated by Django 2.1.1 on 2018-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0008_dvutavr_gost_8239_89'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='mom_iner_Iy',
            field=models.FloatField(),
        ),
    ]
