# Generated by Django 2.1.1 on 2018-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0009_auto_20181009_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='gost_sortamenta',
            name='img_gost',
            field=models.ImageField(default=1, upload_to='sortament\\static\\sortament\\media'),
            preserve_default=False,
        ),
    ]
