# Generated by Django 2.1.1 on 2018-10-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0010_gost_sortamenta_img_gost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gost_sortamenta',
            options={'verbose_name': 'ГОСТы Сортаментов', 'verbose_name_plural': 'fffff'},
        ),
    ]
