# Generated by Django 2.1.1 on 2018-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0016_auto_20181010_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gost_sortamenta',
            name='img_gost',
            field=models.ImageField(upload_to='sortament/'),
        ),
    ]
