# Generated by Django 2.1.2 on 2018-10-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0017_auto_20181010_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='truby_gost_10704_91',
            name='Nomer_gosta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sortament.gost_sortamenta', verbose_name='Номер госта'),
        ),
    ]
