# Generated by Django 2.1.2 on 2018-10-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0018_truby_gost_10704_91_nomer_gosta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truby_gost_10704_91',
            name='Gost_naz',
        ),
    ]
