# Generated by Django 2.1.2 on 2018-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0020_auto_20181029_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gost_sortamenta',
            name='Gost_naz',
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='nomer_dvutavra',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='radius_vnutrennego_zakrugleniya_R',
            field=models.FloatField(verbose_name='Радиус внут'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='radius_zakrugleniya_polki_r',
            field=models.FloatField(verbose_name='Радиус зак полки'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='shirina_pilki_b',
            field=models.IntegerField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='srednyaya_tolsina_polki_t',
            field=models.FloatField(verbose_name='Сред толщ'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='tolshina_stenki_s',
            field=models.FloatField(verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='dvutavr_gost_8239_89',
            name='vysota_h',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='gost_sortamenta',
            name='GOST',
            field=models.CharField(max_length=250, verbose_name='Название ГОСТа'),
        ),
        migrations.AlterField(
            model_name='gost_sortamenta',
            name='img_gost',
            field=models.ImageField(upload_to='sortament/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gost_sortamenta',
            name='type',
            field=models.CharField(choices=[('Труба', 'Труба'), ('Двутавр', 'Двутавр')], max_length=250, verbose_name='Тип проката'),
        ),
    ]
