# Generated by Django 2.1.2 on 2018-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortament', '0021_auto_20181029_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truby_gost_10704_91',
            name='Diametr',
            field=models.FloatField(verbose_name='Диаметр'),
        ),
    ]
