# Generated by Django 2.1.1 on 2018-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spisok_raschetov',
            name='url_rascheta',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
