# Generated by Django 2.1.1 on 2018-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_spisok_raschetov_url_rascheta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_raschetov',
            name='url_rascheta',
            field=models.CharField(max_length=250),
        ),
    ]
