# Generated by Django 2.1.1 on 2018-09-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armatura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armatura',
            old_name='diametr',
            new_name='Дим',
        ),
    ]
