# Generated by Django 2.1.1 on 2018-09-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armatura', '0002_auto_20180925_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armatura',
            old_name='ploshad',
            new_name='Вес',
        ),
        migrations.RenameField(
            model_name='armatura',
            old_name='Дим',
            new_name='Диметр',
        ),
        migrations.RenameField(
            model_name='armatura',
            old_name='ves_armatury',
            new_name='Площадь',
        ),
    ]
