# Generated by Django 2.1.1 on 2018-09-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armatura', '0003_auto_20180925_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armatura',
            old_name='Диметр',
            new_name='Диаметр',
        ),
    ]
