# Generated by Django 2.1.1 on 2018-09-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armatura', '0004_auto_20180925_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armatura',
            old_name='Диаметр',
            new_name='Dim',
        ),
        migrations.RenameField(
            model_name='armatura',
            old_name='Площадь',
            new_name='Plosh',
        ),
        migrations.RenameField(
            model_name='armatura',
            old_name='Вес',
            new_name='Ves',
        ),
    ]
