# Generated by Django 2.1.1 on 2018-09-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armatura', '0005_auto_20180926_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='armatura',
            new_name='sortam_armatura',
        ),
    ]
