# Generated by Django 2.1.1 on 2018-10-18 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baza_dannyh_sojya_polka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodavcy',
            name='Data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
    ]
