# Generated by Django 2.1.1 on 2018-10-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_dannyh_sojya_polka', '0002_prodavcy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazvanie_tovara', models.CharField(max_length=250, verbose_name='Товар')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('Data', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('komu_prenadlejyt_tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baza_dannyh_sojya_polka.prodavcy', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
