# Generated by Django 2.1.2 on 2018-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_dannyh_sojya_polka', '0004_gost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GOST',
        ),
    ]
