# Generated by Django 2.1.2 on 2018-10-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_dannyh_sojya_polka', '0006_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='truby_gost_10704_91',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diametr', models.IntegerField(verbose_name='Диаметор')),
                ('Tolshina_stenki', models.IntegerField(verbose_name='Толщина стенки')),
                ('Gost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baza_dannyh_sojya_polka.sort', verbose_name='Номер госта')),
            ],
            options={
                'verbose_name': 'Труба',
                'verbose_name_plural': 'Трубы',
            },
        ),
    ]
