# Generated by Django 2.1.2 on 2018-10-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_dannyh_sojya_polka', '0007_truby_gost_10704_91'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truby_gost_10704_91',
            name='Gost',
        ),
        migrations.DeleteModel(
            name='sort',
        ),
        migrations.DeleteModel(
            name='truby_gost_10704_91',
        ),
    ]
